CREATE TABLE "patient" (
  "patient_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL
);

CREATE TABLE "medication" (
  "rx_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" int,
  "rx_name" varchar NOT NULL,
  "administered" TIMESTAMP NOT NULL
);

ALTER TABLE "medication" ADD FOREIGN KEY ("patient_id") REFERENCES "patient" ("patient_id");
