// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: medication.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createMedication = `-- name: CreateMedication :one
INSERT INTO medication (
    patient_id,
    rx_name,
    administered
) VALUES (
    $1, $2, $3
)  RETURNING rx_id, patient_id, rx_name, administered
`

type CreateMedicationParams struct {
	PatientID    sql.NullInt32 `json:"patient_id"`
	RxName       string        `json:"rx_name"`
	Administered time.Time     `json:"administered"`
}

func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) (Medication, error) {
	row := q.db.QueryRowContext(ctx, createMedication, arg.PatientID, arg.RxName, arg.Administered)
	var i Medication
	err := row.Scan(
		&i.RxID,
		&i.PatientID,
		&i.RxName,
		&i.Administered,
	)
	return i, err
}
