// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Medication struct {
	RxID         sql.NullInt32 `json:"rx_id"`
	PatientID    sql.NullInt32 `json:"patient_id"`
	RxName       string        `json:"rx_name"`
	Administered time.Time     `json:"administered"`
}

type Patient struct {
	PatientID int32  `json:"patient_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}
